/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FirstProject;
import java.util.Scanner;

public class FirstProject {
    
    public static void main(String[] args) {
        System.out.println("Olá Java!");
        // Cria um leitor para entrada e saida de dados,importado do pacote Scanner
        Scanner leitor = new Scanner(System.in);
        // agora cria a varialvel para poder ler e guardar 
        int idade = leitor.nextInt();
        float cotacaoDolar = leitor.nextFloat();
        double cotacaoEuro = leitor.nextDouble();
        // Para textos nextLine lê uma frase inteira, até ser pressionado o enter
        //e next que lê apenas uma palavra
       String nome = leitor.nextLine();
       String nomeRua = leitor.next();
       
     // Variaveis Tipos e Operadores
     
     // variaveis primitivas
     int inteiro = 0;
     float numeroreal = 6.5f;
     double numeroreal2 = 4.5d;
     char umaletra = 'M';
     byte numericainteira = 0;
     boolean valoreslogicos = false;
     
     // variavel não primitiva
     String palavra = "Texto para uma variavel do tipo String";
     
     // operadores aritimeticos 
    // são os mesmo soma, divisão, substração, multiplicação e resto(%)
    
   //Estruturas Condicionais
   if(numeroreal <= 5){
       
   }
   // estrutura escolha caso 
   int codProduto = 2;
   
   switch(codProduto){
       case 1:  
           break; // todo case deve ter um break! Se não ele executa o próximo case
       case 2:
           break;
       default:  // Um valor que não exista em outros caso(tipo um else no when)
           
   }
   
   
     
     
     
       
        
        
        
        
    }
}
