/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercise16;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
      /*
        16. Escreva um algoritmo que leia o nome e as três notas obtidas por 
        um aluno durante o semestre. Calcular a sua média (aritmética), informar o 
        nome e sua menção aprovado (media >= 7), Reprovado (media <= 5) e 
        Recuperação (media entre 5.1 a 6.9);
        */
      
      System.out.println("Olá para começarmos me informe seu nome");
      String nome = leitor.nextLine();
      System.out.println("Ok " + nome +  " me informe as três notas sua ");
      double n1 = leitor.nextDouble();
      double n2 = leitor.nextDouble();
      double n3 = leitor.nextDouble();
      double media = (n1+n2+n3)/3;
      if(media>= 7.0){
              System.out.println(" Parabéns sua média é " + media +
                      " e você foi aprovado!");
      } else if(media >=5.1 && media <= 6.9){
          System.out.println(" Sua média é " + media +
                      " você está de recuperação!");
      }else{
          System.out.println("Sua média é " + media + "infelizmente foi reprovado!");
      }
    }
}
