/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercisesLP;
import java.util.Scanner;
public class App {
    
    

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);  
        /*
        15. Faça um algoritmo que receba um 
        número e diga se este número está no intervalo entre 100 e 200;
        */
        System.out.println("Olá, me informe um número para verifarmos"
                + "se ele está no intervalo de 100 a 200");
        int numero = leitor.nextInt();
        if(numero >= 100 
                && numero <= 200){
            System.out.println("O número" +numero+ "está entre o 100 e 200");
        } else{
            System.out.println("O número" +numero+ " não está no intervalo");
        } 
        
    }
}
