/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IMCwithClass;
import java.util.Scanner;
public class App {
    

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        Pessoa objetoPessoa = new Pessoa(65.00d, 1.76d); // aqui eu instancio um objeto do tipo pessoa 
        
        System.out.println("Olá vamos calcular o IMC, primeiro me informe "
                + "o seu peso em kgs: ");
        objetoPessoa.setPeso(leitor.nextFloat());
       
        System.out.println("Agora me informe a sua altura em metros: ");
        objetoPessoa.setAltura(leitor.nextFloat());
        
        System.out.println("O seu IMC é: " + objetoPessoa.calcularIMC());
    }
}
