/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercise22;
import java.util.Scanner;
public class App {
    

    public static void main(String[] args) {
        /*
        22. Fa�a um algoritmo que receba o pre�o de custo e o pre�o de venda de 40 produtos.
        Mostre como resultado se houve lucro, preju�zo ou empate para cada produto. 
        Informe o valor de custo de cada produto, o valor 
de venda de cada produto, am�dia de pre�o de custo e do pre�o de venda;
        */
        Scanner leitor = new Scanner(System.in);
        String nomeProduto;
        float precoCusto;
        float precoVenda;
        float lucro ;
        float totalCusto = 0.0f;
        float totalVenda = 0.0f;
        int i=0;
        for(; i<5; i++){
            
            System.out.println("Me informe o nome do produto ");
            nomeProduto = leitor.next();
            
            System.out.println("Me informe o preço de custo do produto ");
            precoCusto = leitor.nextFloat();
            
            System.out.println("Me informe o preço de venda do produto ");
            precoVenda = leitor.nextFloat();
            
            lucro = precoVenda - precoCusto;
            totalCusto = totalCusto + precoCusto;
            totalVenda = totalVenda + precoVenda;
            if(lucro == 0){
                System.out.println("Empate!");
            }
            else if(lucro < 0){
                System.out.println("Não houve lucro, na verdade você perdeu "
                        +(-1*lucro)+ " reais");
            } else{
                System.out.println("O lucro do produto foi de "
                        +lucro+ " reais");
            }
        }
        
        System.out.println("A média total do preço de custo é: " 
                +(totalCusto / i));
        System.out.println("A média total do preço de venda é: "
                + "" +(totalVenda / i));
    }
}