/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioLacoRepeticao;
import java.util.Scanner;
public class App {
    
    

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        /*
        Faça um algoritmo que receba “N” números e mostre positivo,
        negativo ou zero para cada número;
        */
        char continua = 'S';
        while(continua == 's' || continua == 'S' ){
            System.out.println("Olá me informa um número para saber se é"
                    + "negativo ou possitivo");
            double numero = leitor.nextDouble();
            if(numero == 0){
                System.out.println("O número é zero");
            }
            else if(numero < 0){
                System.out.println("O número é negativo");
            }
            else{
                 System.out.println("O número é positvo");
            }
             System.out.println("Deseja continuar?(S/N)");
             continua = leitor.next().charAt(0); // Aqui indica que irá pegar a
             //primeira palavra que digitar e dela vai pegar o primeiro caracter
             
        }
    }   
}
