/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjetoController;
import javax.swing.JOptionPane;
import model.Projeto;

/**
 *
 * @author raian
 */
public class ProjetoDialogTela extends javax.swing.JDialog {

   ProjetoController controller;
   
    public ProjetoDialogTela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new ProjetoController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBarProjeto = new javax.swing.JPanel();
        jLabelProjetoTitle = new javax.swing.JLabel();
        jLabelProjetoSave = new javax.swing.JLabel();
        jPanelProjeto = new javax.swing.JPanel();
        jLabelProjetoNome = new javax.swing.JLabel();
        jTextFieldProjetoNome = new javax.swing.JTextField();
        jLabelProjetoDescricao = new javax.swing.JLabel();
        jScrollPaneProjetoDescricao = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelToolBarProjeto.setBackground(new java.awt.Color(0, 152, 103));

        jLabelProjetoTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelProjetoTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProjetoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProjetoTitle.setText("Projeto");

        jLabelProjetoSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProjetoSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jLabelProjetoSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjetoSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolBarProjetoLayout = new javax.swing.GroupLayout(jPanelToolBarProjeto);
        jPanelToolBarProjeto.setLayout(jPanelToolBarProjetoLayout);
        jPanelToolBarProjetoLayout.setHorizontalGroup(
            jPanelToolBarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjetoTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelProjetoSave, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelToolBarProjetoLayout.setVerticalGroup(
            jPanelToolBarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarProjetoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelToolBarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProjetoTitle)
                    .addComponent(jLabelProjetoSave))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanelProjeto.setBackground(new java.awt.Color(255, 255, 255));

        jLabelProjetoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelProjetoNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProjetoNome.setText("Nome");

        jTextFieldProjetoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldProjetoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProjetoNomeActionPerformed(evt);
            }
        });

        jLabelProjetoDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelProjetoDescricao.setText("Descrição");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaDescricao.setRows(5);
        jScrollPaneProjetoDescricao.setViewportView(jTextAreaDescricao);

        javax.swing.GroupLayout jPanelProjetoLayout = new javax.swing.GroupLayout(jPanelProjeto);
        jPanelProjeto.setLayout(jPanelProjetoLayout);
        jPanelProjetoLayout.setHorizontalGroup(
            jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetoLayout.createSequentialGroup()
                .addGroup(jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProjetoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneProjetoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jLabelProjetoNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldProjetoNome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelProjetoLayout.setVerticalGroup(
            jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjetoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldProjetoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelProjetoDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneProjetoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBarProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelProjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBarProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProjetoSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjetoSaveMouseClicked
      try{
           Projeto projeto = new Projeto();
       projeto.setNome(jTextFieldProjetoNome.getText());
       projeto.setDescricao(jTextAreaDescricao.getText());
       controller.save(projeto);     
       JOptionPane.showMessageDialog(rootPane,"Projeto salvo com sucesso!");   
      } catch(Exception ex){
          JOptionPane.showMessageDialog(rootPane, "Erro ao salvar");
      }
      this.dispose();
       
    }//GEN-LAST:event_jLabelProjetoSaveMouseClicked

    private void jTextFieldProjetoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProjetoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProjetoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoDialogTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoDialogTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoDialogTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoDialogTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjetoDialogTela dialog = new ProjetoDialogTela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelProjetoDescricao;
    private javax.swing.JLabel jLabelProjetoNome;
    private javax.swing.JLabel jLabelProjetoSave;
    private javax.swing.JLabel jLabelProjetoTitle;
    private javax.swing.JPanel jPanelProjeto;
    private javax.swing.JPanel jPanelToolBarProjeto;
    private javax.swing.JScrollPane jScrollPaneProjetoDescricao;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldProjetoNome;
    // End of variables declaration//GEN-END:variables
}
