/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TarefaController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Tarefa;
import javax.swing.JOptionPane;
import model.Projeto;

/**
 *
 * @author raian
 */
public class TarefaDialogTela extends javax.swing.JDialog {

    TarefaController controller;
    Projeto projeto;
  
    public TarefaDialogTela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initDataAccessObjects();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBarTarefa = new javax.swing.JPanel();
        jLabelToolBarTarefaSave = new javax.swing.JLabel();
        jLabelToolBarTarefaTitle = new javax.swing.JLabel();
        jPanelTarefa = new javax.swing.JPanel();
        jLabelNomeTarefa = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelTarefaDescricao = new javax.swing.JLabel();
        jScrollPaneTarefaDescricao = new javax.swing.JScrollPane();
        jTextDescricao = new javax.swing.JTextArea();
        jLabelTarefaPrazo = new javax.swing.JLabel();
        jLabeltarefaObservacao = new javax.swing.JLabel();
        jScrollTarefaObservacao = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jFormattedTextFieldPrazoTarefa = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelToolBarTarefa.setBackground(new java.awt.Color(0, 152, 103));

        jLabelToolBarTarefaSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToolBarTarefaSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jLabelToolBarTarefaSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelToolBarTarefaSaveMouseClicked(evt);
            }
        });

        jLabelToolBarTarefaTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelToolBarTarefaTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelToolBarTarefaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToolBarTarefaTitle.setText("Tarefa");

        javax.swing.GroupLayout jPanelToolBarTarefaLayout = new javax.swing.GroupLayout(jPanelToolBarTarefa);
        jPanelToolBarTarefa.setLayout(jPanelToolBarTarefaLayout);
        jPanelToolBarTarefaLayout.setHorizontalGroup(
            jPanelToolBarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelToolBarTarefaTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelToolBarTarefaSave)
                .addGap(16, 16, 16))
        );
        jPanelToolBarTarefaLayout.setVerticalGroup(
            jPanelToolBarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToolBarTarefaLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanelToolBarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelToolBarTarefaSave)
                    .addComponent(jLabelToolBarTarefaTitle))
                .addContainerGap())
        );

        jPanelTarefa.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNomeTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNomeTarefa.setText("Nome");

        jLabelTarefaDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTarefaDescricao.setText("Descrição");

        jTextDescricao.setColumns(20);
        jTextDescricao.setRows(5);
        jScrollPaneTarefaDescricao.setViewportView(jTextDescricao);

        jLabelTarefaPrazo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTarefaPrazo.setText("Prazo");

        jLabeltarefaObservacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabeltarefaObservacao.setText("Observação");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollTarefaObservacao.setViewportView(jTextArea2);

        jFormattedTextFieldPrazoTarefa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jPanelTarefaLayout = new javax.swing.GroupLayout(jPanelTarefa);
        jPanelTarefa.setLayout(jPanelTarefaLayout);
        jPanelTarefaLayout.setHorizontalGroup(
            jPanelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltarefaObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTarefaPrazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTarefaLayout.createSequentialGroup()
                        .addGroup(jPanelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNomeTarefa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldPrazoTarefa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneTarefaDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jScrollTarefaObservacao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTarefaDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanelTarefaLayout.setVerticalGroup(
            jPanelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTarefaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTarefaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTarefaPrazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldPrazoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltarefaObservacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollTarefaObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBarTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelToolBarTarefaSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelToolBarTarefaSaveMouseClicked
      try{
           Tarefa tarefa = new Tarefa();
       tarefa.setIdprojeto(projeto.getId());
       tarefa.setNome(jTextFieldNome.getText());
       tarefa.setDescricao(jTextDescricao.getText());
       tarefa.setObservacao(jTextArea2.getText());
       tarefa.isIscompleted();
       
       SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
       Date prazo = null;
       try{
       prazo = dateFormat.parse(jFormattedTextFieldPrazoTarefa.getText());
       }catch(ParseException ex){
           Logger.getLogger(TarefaDialogTela.class.getName()).log(Level.SEVERE, null, ex); 
       }
       tarefa.setPrazo(prazo);
       
       controller.save(tarefa); 
       
       JOptionPane.showMessageDialog(rootPane,"Tarefa salva com sucesso!");   
      } catch(Exception ex){
          JOptionPane.showMessageDialog(rootPane, ex.getMessage());
      }
      this.dispose();
       
                                   
    }//GEN-LAST:event_jLabelToolBarTarefaSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarefaDialogTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarefaDialogTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarefaDialogTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarefaDialogTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TarefaDialogTela dialog = new TarefaDialogTela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldPrazoTarefa;
    private javax.swing.JLabel jLabelNomeTarefa;
    private javax.swing.JLabel jLabelTarefaDescricao;
    private javax.swing.JLabel jLabelTarefaPrazo;
    private javax.swing.JLabel jLabelToolBarTarefaSave;
    private javax.swing.JLabel jLabelToolBarTarefaTitle;
    private javax.swing.JLabel jLabeltarefaObservacao;
    private javax.swing.JPanel jPanelTarefa;
    private javax.swing.JPanel jPanelToolBarTarefa;
    private javax.swing.JScrollPane jScrollPaneTarefaDescricao;
    private javax.swing.JScrollPane jScrollTarefaObservacao;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextDescricao;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }
    private void initDataAccessObjects() {
     controller = new TarefaController();
    }

}
