/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjetoController;
import controller.TarefaController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import model.Projeto;
import model.Tarefa;
import util.TarefaTableModel;

/**
 *
 * @author raian
 */
public final class TelaPrincipal extends javax.swing.JFrame {
    
    ProjetoController projetoController;
    TarefaController tarefaController;
    
    DefaultListModel projetosModel;
    TarefaTableModel tarefaModel;
    
  
    public TelaPrincipal() throws Exception {
        initComponents();
        initDataController();
        decorateTableTarefa();
        
        
        initComponentsModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBar = new javax.swing.JPanel();
        JLabelToolBarTitle = new javax.swing.JLabel();
        JLabelToolBarSubtitle = new javax.swing.JLabel();
        jPanelProjetos = new javax.swing.JPanel();
        jLabelProjetosTitle = new javax.swing.JLabel();
        jLabelProjetosAdd = new javax.swing.JLabel();
        jPanelTarefas = new javax.swing.JPanel();
        jLabelTarefaTitle = new javax.swing.JLabel();
        jLabelTarefaAdd = new javax.swing.JLabel();
        jPanelProjetoList = new javax.swing.JPanel();
        jScrollPaneProjetos = new javax.swing.JScrollPane();
        jListProjetos = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        jPanelEmptyList = new javax.swing.JPanel();
        jLabelEmptyListIcon = new javax.swing.JLabel();
        jLabelEmptyListTitle = new javax.swing.JLabel();
        jLabelEmptyListSubtitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanelToolBar.setBackground(new java.awt.Color(0, 153, 102));

        JLabelToolBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JLabelToolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
        JLabelToolBarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        JLabelToolBarTitle.setText(" ToDoApp");

        JLabelToolBarSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        JLabelToolBarSubtitle.setText("Anote tudo não esqueça nada!");

        javax.swing.GroupLayout jPanelToolBarLayout = new javax.swing.GroupLayout(jPanelToolBar);
        jPanelToolBar.setLayout(jPanelToolBarLayout);
        jPanelToolBarLayout.setHorizontalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelToolBarSubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelToolBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelToolBarLayout.setVerticalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(JLabelToolBarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelToolBarSubtitle)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelProjetos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProjetos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelProjetosTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProjetosTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelProjetosTitle.setText("Projetos");

        jLabelProjetosAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelProjetosAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjetosAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelProjetosLayout = new javax.swing.GroupLayout(jPanelProjetos);
        jPanelProjetos.setLayout(jPanelProjetosLayout);
        jPanelProjetosLayout.setHorizontalGroup(
            jPanelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetosLayout.createSequentialGroup()
                .addComponent(jLabelProjetosTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelProjetosAdd)
                .addContainerGap())
        );
        jPanelProjetosLayout.setVerticalGroup(
            jPanelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjetosLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProjetosAdd)
                    .addComponent(jLabelProjetosTitle))
                .addGap(23, 23, 23))
        );

        jPanelTarefas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTarefas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTarefaTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTarefaTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelTarefaTitle.setText("Tarefas");

        jLabelTarefaAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelTarefaAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTarefaAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTarefasLayout = new javax.swing.GroupLayout(jPanelTarefas);
        jPanelTarefas.setLayout(jPanelTarefasLayout);
        jPanelTarefasLayout.setHorizontalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTarefaTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                .addComponent(jLabelTarefaAdd)
                .addGap(17, 17, 17))
        );
        jPanelTarefasLayout.setVerticalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTarefasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTarefaTitle)
                    .addComponent(jLabelTarefaAdd))
                .addGap(23, 23, 23))
        );

        jPanelProjetoList.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProjetoList.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jListProjetos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jListProjetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProjetos.setFixedCellHeight(45);
        jListProjetos.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jListProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProjetosMouseClicked(evt);
            }
        });
        jScrollPaneProjetos.setViewportView(jListProjetos);

        javax.swing.GroupLayout jPanelProjetoListLayout = new javax.swing.GroupLayout(jPanelProjetoList);
        jPanelProjetoList.setLayout(jPanelProjetoListLayout);
        jPanelProjetoListLayout.setHorizontalGroup(
            jPanelProjetoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneProjetos, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelProjetoListLayout.setVerticalGroup(
            jPanelProjetoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableTarefas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTarefas.setGridColor(new java.awt.Color(255, 255, 255));
        jTableTarefas.setRowHeight(45);
        jTableTarefas.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jTableTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTarefas.setShowHorizontalLines(true);
        jTableTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTarefasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTarefas);

        jPanelEmptyList.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        jLabelEmptyListTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmptyListTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelEmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptyListTitle.setText("Nenhuma tarefa ");
        jLabelEmptyListTitle.setToolTipText("");

        jLabelEmptyListSubtitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelEmptyListSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptyListSubtitle.setText("Clique no botão \"+\" para adicionar a tarefa");

        javax.swing.GroupLayout jPanelEmptyListLayout = new javax.swing.GroupLayout(jPanelEmptyList);
        jPanelEmptyList.setLayout(jPanelEmptyListLayout);
        jPanelEmptyListLayout.setHorizontalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmptyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                        .addGroup(jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEmptyListSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanelEmptyListLayout.setVerticalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabelEmptyListIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEmptyListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEmptyListSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelEmptyList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(43, 43, 43)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEmptyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProjetoList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjetoList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProjetosAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjetosAddMouseClicked
        // TODO add your handling code here:
        ProjetoDialogTela projetoDialogTela = new ProjetoDialogTela(this, rootPaneCheckingEnabled);
        projetoDialogTela.setVisible(true);
        
        projetoDialogTela.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e){
                try {
                    loadProjetos();
                } catch (Exception ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }   
        });
        
    }//GEN-LAST:event_jLabelProjetosAddMouseClicked

    public void decorateTableTarefa(){
    // customizando o header da table de tarefas
    jTableTarefas.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
    jTableTarefas.getTableHeader().setBackground (new Color(0, 153, 102));
    jTableTarefas.getTableHeader().setForeground (new Color(255, 255, 255));
   // Cria uma sort automatico, possibilitando a ordenação das colunas
    jTableTarefas.setAutoCreateRowSorter(true);
}
    
    
    private void jLabelTarefaAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTarefaAddMouseClicked
      TarefaDialogTela tarefaDialogTela = new TarefaDialogTela(this, rootPaneCheckingEnabled);
      Projeto projeto = (Projeto) projetosModel.get(jListProjetos.getSelectedIndex());
      tarefaDialogTela.setProjeto(projeto);
      tarefaDialogTela.setVisible(true);

    }//GEN-LAST:event_jLabelTarefaAddMouseClicked

    private void jTableTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTarefasMouseClicked
        try {
            int rowIndex = jTableTarefas.rowAtPoint(evt.getPoint());
            int columnIndex = jTableTarefas.columnAtPoint(evt.getPoint());
            
            if(columnIndex == 3){
                Tarefa tarefa = tarefaModel.getTarefas().get(rowIndex);
                tarefaController.update(tarefa);
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableTarefasMouseClicked

    private void jListProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProjetosMouseClicked
        int projetoIndex =jListProjetos.getSelectedIndex();
        Projeto projeto = (Projeto) projetosModel.get(projetoIndex); //aqui fazemos um cast, porque nosso porjetoModel é um object
        // (Projeto)desta forma seta que meu object projetoModel é um projeto, seria um cast
        loadTarefas(projeto.getId());
        
       
    }//GEN-LAST:event_jListProjetosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new TelaPrincipal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelToolBarSubtitle;
    private javax.swing.JLabel JLabelToolBarTitle;
    private javax.swing.JLabel jLabelEmptyListIcon;
    private javax.swing.JLabel jLabelEmptyListSubtitle;
    private javax.swing.JLabel jLabelEmptyListTitle;
    private javax.swing.JLabel jLabelProjetosAdd;
    private javax.swing.JLabel jLabelProjetosTitle;
    private javax.swing.JLabel jLabelTarefaAdd;
    private javax.swing.JLabel jLabelTarefaTitle;
    private javax.swing.JList<String> jListProjetos;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEmptyList;
    private javax.swing.JPanel jPanelProjetoList;
    private javax.swing.JPanel jPanelProjetos;
    private javax.swing.JPanel jPanelTarefas;
    private javax.swing.JPanel jPanelToolBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneProjetos;
    private javax.swing.JTable jTableTarefas;
    // End of variables declaration//GEN-END:variables




public void initDataController(){
    projetoController = new ProjetoController();
    tarefaController = new TarefaController();
     
}

public void initComponentsModel() throws Exception {
  projetosModel = new DefaultListModel<Projeto>();
  loadProjetos(); // carregar dados para dentro desse model, para exibir eles
  
  tarefaModel = new TarefaTableModel();
  jTableTarefas.setModel(tarefaModel);
  
 // jTableTarefas.getColumnModel().getColumn(2).setCellRenderer(new StatusColumnCellRenderer());
       // jTableTarefas.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRederer("edit"));
      //  jTableTarefas.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRederer("delete"));

        if (!projetosModel.isEmpty()) {
            jListProjetos.setSelectedIndex(0);

  
            int projectIndex = jListProjetos.getSelectedIndex();
            Projeto projeto =
                    (Projeto) projetosModel.get(projectIndex);
            

           // query.getResultList();

  loadTarefas(projeto.getId());
  
  
}

}
// metodo para selecionar as tarefas pelo projeto 
private void showJTableTarefas(boolean isEmptyTable){
    if(isEmptyTable){
        if(jPanelEmptyList.isVisible()){
            jPanelEmptyList.setVisible(false);
            jPanel5.remove(jPanelEmptyList);
        }
        
        jPanel5.add(jScrollPane1);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(jPanel5.getWidth(), jPanel5.getHeight());
    }else {
        if(jScrollPane1.isVisible()){
            jScrollPane1.setVisible(false);
            jPanel5.remove(jScrollPane1);
        }
        jPanel5.add(jPanelEmptyList);
        jPanelEmptyList.setVisible(true);
        jPanelEmptyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
    }
}

private void loadTarefas(int idprojeto){
    List<Tarefa> tarefas =tarefaController.getByProjetoId(idprojeto);
    tarefaModel.setTarefas(tarefas);
    showJTableTarefas(!tarefas.isEmpty()); // com a ! se transforma em uma pergunta, a lista está vazia?
}
public void loadProjetos() throws Exception {
    List<Projeto> projetos = projetoController.getAll(); // aqui usamos o controller para pegarmos todos projetos
    
   projetosModel.clear(); // limpo o projetosModel, cada vez que cadastrar um projeto, será carregado os projetos do banco
   
   for(int i=0; i< projetos.size(); i++){
       Projeto projeto = projetos.get(i);  // aqui add todos os projetos carregados dentro do model
       projetosModel.addElement(projeto);
   }
   // vincular o model criado com o jList da interface
   jListProjetos.setModel(projetosModel);
}
}



